#include "BIS_AddonInfo.hpp"
// French Army 2035 Mod
// Made for Arma 3
// Made by Hector Corral
// In order to use the content of this addon in your own mod, please contact me on steam.

class CfgPatches
{
	class FR2035_characters_F
	{
		units[]=
		{
			"FR2035_Soldier_base_F",
			"FR2035_Soldier_F",
			"FR2035_Soldier_lite_F",
			"FR2035_Soldier_GL_F",
			"FR2035_soldier_AR_F",
			"FR2035_Soldier_SL_F",
			"FR2035_Soldier_TL_F",
			"FR2035_soldier_M_F",
			"FR2035_soldier_LAT_F",
			"FR2035_medic_F",
			"FR2035_soldier_repair_F",
			"FR2035_soldier_exp_F",
			"FR2035_Soldier_A_F",
			"FR2035_soldier_AT_F",
			"FR2035_soldier_AA_F",
			"FR2035_engineer_F",
			"FR2035_officer_F",
			"FR2035_soldier_PG_F",
			"FR2035_soldier_UAV_F",
			"fr2035_soldier_unarmed_f",
			"fr2035_survivor_F",
			"fr2035_soldier_universal_f",
			"FR2035_Soldier_recon_base",
			"FR2035_recon_F",
			"FR2035_recon_LAT_F",
			"FR2035_recon_exp_F",
			"FR2035_recon_medic_F",
			"FR2035_recon_TL_F",
			"FR2035_recon_M_F",
			"FR2035_recon_JTAC_F",
			"FR2035_Soldier_sniper_base_F",
			"FR2035_sniper_F",
			"FR2035_spotter_F",
			"FR2035_Soldier_diver_base_F",
			"FR2035_diver_F",
			"FR2035_diver_TL_F",
			"FR2035_diver_exp_F",
			"FR2035_Soldier_support_base_F",
			"FR2035_soldier_AAR_F",
			"FR2035_soldier_AAT_F",
			"FR2035_soldier_AAA_F",
			"FR2035_support_MG_F",
			"FR2035_support_GMG_F",
			"FR2035_support_Mort_F",
			"FR2035_support_AMG_F",
			"FR2035_support_AMort_F",
			"FR2035_crew_F"
		};
		weapons[]=
		{
			"U_FR2035_CombatUniform_ce",
			"U_FR2035_CombatUniform_ce_vest",
			"U_FR2035_CombatUniform_ce_tshirt",
			"U_FR2035_GhillieSuit",
			"U_FR2035_survival_uniform",
			"V_FR2035_PlateCarrier_ce",
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"H_FR2035_HelmetB_camo",
			"H_FR2035_HelmetCrew_B",
			"H_FR2035_Beret_blu"
		};
		requiredVersion=1.56;
		requiredAddons[]=
		{
			"FR2035_data_F",
			"FR2035_language_F",
			"FR2035_weapons_F"
		};
		version="18-02-2016";
		author="$STR_fr2035_author";
	};
};

class CfgVehicles {
	class B_Soldier_base_F;

	class FR2035_Soldier_base_F: B_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_base_F";
		faction="FR2035_F";
		genericNames="FrenchMen";
		nakedUniform="U_BasicBody";
		uniformClass="U_FR2035_CombatUniform_ce";
		hiddenSelections[]=
		{
			"Camo",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_uniform_co.paa"
		};
		class EventHandlers;
		weapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_Soldier_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_F";
		scope=2;
		displayName="$STR_A3_CfgVehicles_B_Soldier_F0";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="U_FR2035_CombatUniform_ce";
	};
	class FR2035_Soldier_lite_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_lite_F";
		scope=2;
		displayName="$STR_B_Soldier_lite_F0";
		uniformClass="U_FR2035_CombatUniform_ce";
		weapons[]=
		{
			"arifle_FR2035_MX_ACO_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_ACO_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		camouflage=1.2;
		cost=90000;
		linkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_Beret_blu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_Beret_blu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class FR2035_Soldier_GL_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_GL_F";
		scope=2;
		displayName="$STR_B_Soldier_GL_F0";
		weapons[]=
		{
			"arifle_FR2035_MX_GL_ACO_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_GL_ACO_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		overviewPicture="\A3\Data_F_Mark\Images\watermarkInfo_page09_ca.paa";
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		cost=130000;
		threat[]={1,0.30000001,0.1};
		linkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_soldier_AR_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AR_F";
		scope=2;
		displayName="$STR_B_soldier_AR_F0";
		weapons[]=
		{
			"arifle_FR2035_MX_SW_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_SW_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=125000;
		threat[]={1,0.1,0.30000001};
		icon="iconManMG";
		uniformClass="U_FR2035_CombatUniform_ce";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_Soldier_SL_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_SL_F";
		scope=2;
		displayName="$STR_B_Soldier_SL_F0";
		uniformClass="U_FR2035_CombatUniform_ce";
		weapons[]=
		{
			"arifle_FR2035_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=500000;
		camouflage=1.4;
		icon="iconManLeader";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_Soldier_TL_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_TL_F";
		scope=2;
		displayName="$STR_B_Soldier_TL_F0";
		uniformClass="U_FR2035_CombatUniform_ce";
		weapons[]=
		{
			"arifle_FR2035_MX_GL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_GL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		cost=450000;
		camouflage=1.4;
		icon="iconManLeader";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_soldier_M_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_M_F";
		scope=2;
		displayName="$STR_B_soldier_M_F0";
		weapons[]=
		{
			"arifle_FR2035_MXM_Hamr_LP_BI_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXM_Hamr_LP_BI_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=150000;
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_soldier_LAT_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_LAT_F";
		scope=2;
		displayName="$STR_B_soldier_LAT_F0";
		backpack="B_AssaultPack_rgr_LAT";
		weapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=180000;
		threat[]={1,0.69999999,0.30000001};
		icon="iconManAT";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		secondaryAmmoCoef=0.5;
	};
	class FR2035_medic_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_medic_F";
		scope=2;
		displayName="$STR_B_medic_F0";
		attendant=1;
		weapons[]=
		{
			"arifle_FR2035_MX_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=300000;
		camouflage=1.6;
		icon="iconManMedic";
		uniformClass="U_FR2035_CombatUniform_ce";
		backpack="B_AssaultPack_rgr_Medic";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		picture="pictureHeal";
	};
	class FR2035_soldier_repair_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_repair_F";
		scope=2;
		displayName="$STR_B_soldier_repair_F0";
		engineer=1;
		detectSkill=40;
		cost=220000;
		camouflage=1.6;
		uniformClass="U_FR2035_CombatUniform_ce_tshirt";
		backpack="B_AssaultPack_rgr_Repair";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		weapons[]=
		{
			"arifle_FR2035_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class FR2035_soldier_exp_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_exp_F";
		scope=2;
		displayName="$STR_B_soldier_exp_F0";
		cost=115000;
		camouflage=1.6;
		backpack="B_Kitbag_rgr_Exp";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		canDeactivateMines=1;
		detectSkill=80;
		threat[]={1,0.5,0.1};
		linkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrierGL_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManExplosive";
		picture="pictureExplosive";
	};
	class FR2035_Soldier_A_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_A_F";
		scope=2;
		displayName="$STR_B_Soldier_A_F0";
		weapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		cost=110000;
		camouflage=1.5;
		backpack="B_AssaultPack_mcamo_Ammo";
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_soldier_AT_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AT_F";
		scope=2;
		displayName="$STR_B_soldier_AT_F0";
		backpack="B_AssaultPack_mcamo_AT";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"launch_B_Titan_short_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"launch_B_Titan_short_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AT",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AT",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=190000;
		threat[]={1,1,0.80000001};
		camouflage=1.5;
		icon="iconManAT";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		secondaryAmmoCoef=0.5;
	};
	class FR2035_soldier_AA_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AA_F";
		scope=2;
		displayName="$STR_B_soldier_AA_F0";
		backpack="B_AssaultPack_mcamo_AA";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"launch_B_Titan_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"launch_B_Titan_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AA",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AA",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=200000;
		threat[]={1,1,0.80000001};
		camouflage=1.5;
		icon="iconManAT";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		secondaryAmmoCoef=0.5;
	};
	class FR2035_engineer_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_engineer_F";
		scope=2;
		displayName="$STR_B_engineer_F0";
		cost=220000;
		camouflage=1.6;
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		backpack="B_Kitbag_mcamo_Eng";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		canDeactivateMines=1;
		engineer=1;
		detectSkill=60;
		threat[]={1,0.5,0.1};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class FR2035_crew_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_crew_F";
		uniformClass="U_FR2035_CombatUniform_ce";
		scope=2;
		displayName="$STR_B_crew_F0";
		weapons[]=
		{
			"arifle_FR2035_MXC_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=90000;
		camouflage=1.6;
		linkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_HelmetCrew_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_HelmetCrew_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_officer_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_officer_F";
		scope=2;
		displayName="$STR_B_officer_F0";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_casual"
		};
		weapons[]=
		{
			"arifle_FR2035_MXC_Aco_F",
			"hgun_Pistol_heavy_01_MRD_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Aco_F",
			"hgun_Pistol_heavy_01_MRD_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=600000;
		camouflage=1.6;
		icon="iconManOfficer";
		linkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_Beret_blu",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_rgr",
			"H_FR2035_Beret_blu",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class FR2035_soldier_PG_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_PG_F";
		scope=2;
		displayName="$STR_B_soldier_PG_F0";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		backpack="B_Parachute";
		cost=120000;
	};
	class FR2035_soldier_UAV_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_UAV_F";
		scope=2;
		displayName="$STR_A3_B_SOLDIER_UAV_F0";
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		backpack="B_UAV_01_backpack_F";
		cost=150000;
		uavHacker=1;
	};
	class fr2035_soldier_unarmed_f: FR2035_Soldier_F
	{
		_generalMacro="fr2035_soldier_unarmed_f";
		displayName="$STR_A3_CfgVehicles_b_soldier_unarmed_f_displayName";
		author="$STR_fr2035_author";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		RespawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_FR2035_PlateCarrier_ce",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class fr2035_survivor_F: FR2035_Soldier_F
	{
		_generalMacro="fr2035_survivor_F";
		displayName="$STR_A3_CfgVehicles_b_survivor_f_displayName";
		author="$STR_fr2035_author";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		RespawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		Items[]={};
		RespawnItems[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
	};
	class fr2035_soldier_universal_f: FR2035_Soldier_F
	{
		_generalMacro="fr2035_soldier_universal_f";
		scope=1;
		displayName="$STR_A3_CfgVehicles_b_soldier_universal_f_displayName";
		attendant=1;
		engineer=1;
		canDeactivateMines=1;
	};
	class FR2035_Soldier_diver_base_F: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_diver_s"
				};
				speechPlural[]=
				{
					"veh_infantry_diver_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_diver_s";
		textPlural="$STR_A3_nameSound_veh_infantry_diver_p";
		nameSound="veh_infantry_diver_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_diver_base_F";
		scope=0;
		displayName="$STR_B_Soldier_diver_base_F0";
		vehicleClass="MenDiver";
		editorSubcategory="EdSubcat_Personnel_SpecialForces";
		uniformClass="U_FR2035_survival_uniform";
		hiddenSelections[]=
		{
			"Camo",
			"Camo3",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_uniform_co.paa",
			"\fr2035_characters_f\data\fr2035_uniform_tshirt_blue_co.paa"
		};
		hiddenUnderwaterSelections[]=
		{
			"hide"
		};
		shownUnderwaterSelections[]=
		{
			"unhide",
			"unhide2"
		};
		hiddenUnderwaterSelectionsTextures[]=
		{
			"\A3\characters_f\common\data\diver_equip_nato_co.paa",
			"\A3\characters_f\common\data\diver_equip_nato_co.paa",
			"\A3\characters_f\data\visors_ca.paa"
		};
		selectionPersonality="personality";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		linkedItems[]=
		{
			"V_RebreatherB",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_RebreatherB",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_SDAR_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_SDAR_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"20Rnd_556x45_UW_mag",
			"20Rnd_556x45_UW_mag",
			"20Rnd_556x45_UW_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShellBlue",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"20Rnd_556x45_UW_mag",
			"20Rnd_556x45_UW_mag",
			"20Rnd_556x45_UW_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShellBlue",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		primaryAmmoCoef=0.40000001;
		secondaryAmmoCoef=0.1;
		handgunAmmoCoef=0.2;
	};
	class FR2035_diver_F: FR2035_Soldier_diver_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_diver_F";
		scope=2;
		displayName="$STR_B_diver_F0";
		backpack="B_Assault_Diver";
		model="\A3\Characters_F_EPA\BLUFOR\b_soldier_survival_01.p3d";
		modelSides[]={3,1};
		cost=70000;
		camouflage=2;
	};
	class FR2035_diver_TL_F: FR2035_Soldier_diver_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_diver_TL_F";
		scope=2;
		displayName="$STR_B_diver_TL_F0";
		linkedItems[]=
		{
			"V_RebreatherB",
			"G_B_Diving",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_RebreatherB",
			"G_B_Diving",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManLeader";
		cost=430000;
		camouflage=2;
	};
	class FR2035_diver_exp_F: FR2035_Soldier_diver_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_diver_exp_F";
		scope=2;
		backpack="B_AssaultPack_blk_DiverExp";
		displayName="$STR_B_diver_exp_F0";
		canDeactivateMines=1;
		cost=90000;
		camouflage=2;
		icon="iconManExplosive";
	};
	class FR2035_Soldier_recon_base: FR2035_Soldier_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_SF_s"
				};
				speechPlural[]=
				{
					"veh_infantry_SF_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_SF_s";
		textPlural="$STR_A3_nameSound_veh_infantry_SF_p";
		nameSound="veh_infantry_SF_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_recon_base";
		scope=0;
		displayName="$STR_B_Soldier_recon_base0";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		modelSides[]={3,1};
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		armor=2;
		armorStructural=0.5;
		explosionShielding=0.050000001;
		vehicleClass="MenRecon";
		editorSubcategory="EdSubcat_Personnel_SpecialForces";
		camouflage=0.60000002;
		detectSkill=30;
	};
	class FR2035_recon_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_F";
		scope=2;
		displayName="$STR_B_recon_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		weapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=100000;
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_recon_LAT_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_LAT_F";
		scope=2;
		displayName="$STR_B_recon_LAT_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		backpack="B_AssaultPack_rgr_ReconLAT";
		weapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"launch_NLAW_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"launch_NLAW_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		threat[]={1,0.60000002,0.1};
		cost=150000;
		icon="iconManAT";
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		secondaryAmmoCoef=0.5;
	};
	class FR2035_recon_exp_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_exp_F";
		scope=2;
		displayName="$STR_B_recon_exp_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		backpack="B_AssaultPack_rgr_ReconExp";
		weapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Camo_ACO_pointer_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		canDeactivateMines=1;
		detectSkill=80;
		cost=115000;
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManExplosive";
		picture="pictureExplosive";
	};
	class FR2035_recon_medic_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_medic_F";
		scope=2;
		displayName="$STR_B_recon_medic_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		attendant=1;
		weapons[]=
		{
			"arifle_FR2035_MXC_Camo_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXC_Camo_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		cost=290000;
		backpack="B_AssaultPack_rgr_ReconMedic";
		icon="iconManMedic";
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		picture="pictureHeal";
	};
	class FR2035_recon_TL_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_TL_F";
		scope=2;
		displayName="$STR_B_recon_TL_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		weapons[]=
		{
			"arifle_FR2035_MX_Camo_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Camo_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		cost=440000;
		icon="iconManLeader";
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_recon_M_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_M_F";
		scope=2;
		displayName="$STR_B_recon_M_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		weapons[]=
		{
			"arifle_FR2035_MXM_Camo_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MXM_Camo_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=140000;
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		primaryAmmoCoef=0.2;
		secondaryAmmoCoef=0.050000001;
		handgunAmmoCoef=0.1;
	};
	class FR2035_recon_JTAC_F: FR2035_Soldier_recon_base
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_recon_JTAC_F";
		scope=2;
		displayName="$STR_B_recon_JTAC_F0";
		uniformClass="U_FR2035_CombatUniform_ce_vest";
		weapons[]=
		{
			"arifle_FR2035_MX_GL_Camo_Holo_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_GL_Camo_Holo_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		cost=200000;
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB_camo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_Soldier_sniper_base_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_sniper_base_F";
		scope=0;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_sniper"
		};
		displayName="$STR_B_Soldier_sniper_base_F0";
		vehicleClass="MenSniper";
		editorSubcategory="EdSubcat_Personnel_SpecialForces";
		uniformClass="U_FR2035_GhillieSuit";
		model="A3\Characters_F\BLUFOR\b_sniper.p3d";
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		primaryAmmoCoef=0.2;
		secondaryAmmoCoef=0.050000001;
		handgunAmmoCoef=0.1;
	};
	class FR2035_spotter_F: FR2035_Soldier_sniper_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_SF_s"
				};
				speechPlural[]=
				{
					"veh_infantry_SF_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_SF_s";
		textPlural="$STR_A3_nameSound_veh_infantry_SF_p";
		nameSound="veh_infantry_SF_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_spotter_F";
		scope=2;
		displayName="$STR_B_spotter_F0";
		cost=250000;
		threat[]={1,0.30000001,0.30000001};
		camouflage=0.60000002;
		weapons[]=
		{
			"arifle_FR2035_MX_Camo_Hamr_pointer_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Camo_Hamr_pointer_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"Laserbatteries",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"Laserbatteries",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class FR2035_sniper_F: FR2035_Soldier_sniper_base_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		author="$STR_fr2035_author";
		_generalMacro="FR2035_sniper_F";
		scope=2;
		displayName="$STR_B_sniper_F0";
		weapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=350000;
		threat[]={1,0.30000001,0.30000001};
		camouflage=0.60000002;
	};
	class FR2035_Soldier_support_base_F: FR2035_Soldier_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_Soldier_support_base_F";
		scope=0;
		camouflage=1.5;
		displayName="$STR_FR2035_Soldier_support_base_F0";
		vehicleClass="MenSupport";
		editorSubcategory="EdSubcat_Personnel";
		uniformClass="U_FR2035_CombatUniform_ce_tshirt";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_uniform_co.paa",
			"\fr2035_characters_f\data\fr2035_uniform_tshirt_co.paa"
		};
		weapons[]=
		{
			"arifle_FR2035_MX_Aco_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_FR2035_MX_Aco_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_FR2035_HelmetB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class FR2035_soldier_AAR_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AAR_F";
		scope=2;
		displayName="$STR_O_SOLDIERU_AAR_F0";
		cost=95000;
		backpack="B_Kitbag_rgr_AAR";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		modelSides[]={3,1};
	};
	class FR2035_soldier_AAT_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AAT_F";
		scope=2;
		displayName="$STR_B_soldier_AAT_F0";
		cost=93000;
		backpack="B_Carryall_mcamo_AAT";
	};
	class FR2035_soldier_AAA_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_soldier_AAA_F";
		scope=2;
		displayName="$STR_B_soldier_AAA_F0";
		cost=94000;
		backpack="B_Carryall_mcamo_AAA";
	};
	class FR2035_support_MG_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_support_MG_F";
		scope=2;
		displayName="$STR_B_support_MG_F0";
		backpack="B_HMG_01_weapon_F";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		threat[]={1,0.30000001,0.30000001};
		cost=460000;
	};
	class FR2035_support_GMG_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_support_GMG_F";
		scope=2;
		displayName="$STR_B_support_GMG_F0";
		backpack="B_GMG_01_weapon_F";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		threat[]={1,0.60000002,0.1};
		cost=470000;
	};
	class FR2035_support_Mort_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_support_Mort_F";
		scope=2;
		displayName="$STR_B_support_Mort_F0";
		backpack="B_Mortar_01_weapon_F";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		threat[]={1,0.80000001,0.1};
		cost=480000;
	};
	class FR2035_support_AMG_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_support_AMG_F";
		scope=2;
		displayName="$STR_B_support_AMG_F0";
		backpack="B_HMG_01_support_F";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		cost=91000;
	};
	class FR2035_support_AMort_F: FR2035_Soldier_support_base_F
	{
		author="$STR_fr2035_author";
		_generalMacro="FR2035_support_AMort_F";
		scope=2;
		displayName="$STR_B_support_AMort_F0";
		backpack="B_Mortar_01_support_F";
		weapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_FR2035_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		cost=81000;
	};
};

class cfgWeapons {
	class U_B_CombatUniform_mcam;
	class U_B_CombatUniform_mcam_tshirt;
	class U_B_CombatUniform_mcam_vest;
	class U_B_GhillieSuit;
	class U_B_survival_uniform;
    class UniformItem;
	class V_PlateCarrier1_rgr;
	class V_PlateCarrier2_rgr;
	class VestItem;
	class H_HelmetB;
	class H_HelmetB_camo;
	class H_HelmetCrew_B;
	class H_Beret_blk;
    
	class U_FR2035_CombatUniform_ce: U_B_CombatUniform_mcam
	{
		author="$STR_fr2035_author";
		displayName="$STR_fr2035_combat_fatigues";
		picture="\fr2035_characters_f\data\fr2035_uniform_icon_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_suitpack_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="FR2035_Soldier_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class U_FR2035_CombatUniform_ce_tshirt: U_B_CombatUniform_mcam_tshirt
	{
		author="$STR_fr2035_author";
		displayName="$STR_fr2035_combat_fatigues_tee";
		picture="\fr2035_characters_f\data\fr2035_uniform_icon_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_suitpack_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="FR2035_soldier_AAR_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class U_FR2035_CombatUniform_ce_vest: U_B_CombatUniform_mcam_vest
	{
		author="$STR_fr2035_author";
		displayName="$STR_fr2035_recon_fatigues";
		picture="\fr2035_characters_f\data\fr2035_uniform_icon_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_suitpack_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="FR2035_recon_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class U_FR2035_GhillieSuit: U_B_GhillieSuit
	{
		author="$STR_fr2035_author";
		displayName="$STR_fr2035_ghillie_suit";
		picture="\fr2035_characters_f\data\fr2035_uniform_icon_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_suitpack_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="FR2035_sniper_F";
			containerClass="Supply60";
			mass=60;
		};
	};
	class U_FR2035_survival_uniform: U_B_survival_uniform
	{
		author="$STR_fr2035_author";
		displayName="$STR_fr2035_survival_fatigues_F0";
		picture="\fr2035_characters_f\data\fr2035_uniform_icon_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\diver_suit_nato_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="FR2035_diver_F";
			containerClass="Supply40";
			uniformType="Neopren";
			mass=60;
		};
	};
	class V_FR2035_PlateCarrier_ce: V_PlateCarrier1_rgr
	{
		author="$STR_fr2035_author";
		_generalMacro="V_FR2035_PlateCarrier_ce";
		displayName="$STR_fr2035_v_platecarrier1_rgr0";
		picture="\fr2035_characters_f\data\fr2035_vest_icon_ca.paa";
		model="\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_vest_co.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F\BLUFOR\equip_b_vest02";
			containerClass="Supply140";
			mass=80;
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=16;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=16;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class V_FR2035_PlateCarrierGL_ce: V_PlateCarrier2_rgr
	{
		author="$STR_fr2035_author";
		_generalMacro="V_FR2035_PlateCarrierGL_ce";
		displayName="$STR_fr2035_v_platecarrier2_rgr0";
		picture="\fr2035_characters_f\data\fr2035_vest_icon_ca.paa";
		model="\A3\Characters_F\BLUFOR\equip_b_vest01.p3d";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_vest_co.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F\BLUFOR\equip_b_vest01";
			containerClass="Supply140";
			mass=100;
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=20;
					PassThrough=0.2;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=20;
					PassThrough=0.2;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=20;
					passThrough=0.2;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.2;
				};
			};
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class H_FR2035_HelmetB: H_HelmetB
	{
		author="$STR_fr2035_author";
		_generalMacro="H_FR2035_HelmetB";
		displayName="$STR_fr2035_h_helmetb0";
		picture="\fr2035_characters_f\data\fr2035_helmet_icon_ca.paa";
		model="\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_helmet_co.paa"
		};
	};
	class H_FR2035_HelmetB_camo: H_HelmetB_camo
	{
		author="$STR_fr2035_author";
		_generalMacro="H_FR2035_HelmetB_camo";
		displayName="$STR_fr2035_h_helmetb_camo0";
		model="\A3\Characters_F\BLUFOR\headgear_b_helmet_camo";
		picture="\fr2035_characters_f\data\fr2035_helmet_icon_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_helmet_co.paa",
			"\fr2035_characters_f\data\fr2035_helmet_camo_co.paa"
		};
	};
	class H_FR2035_HelmetCrew_B: H_HelmetCrew_B
	{
		author="$STR_fr2035_author";
		_generalMacro="H_FR2035_HelmetCrew_B";
		displayName="$STR_fr2035_h_helmetcrewb0";
		picture="\fr2035_characters_f\data\fr2035_crewhelmet_icon_ca.paa";
		model="\A3\Characters_F\BLUFOR\headgear_b_helmet_crew";
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_crewhelmet_co.paa"
		};
	};
	class H_FR2035_Beret_blu: H_Beret_blk
	{
		author="$STR_fr2035_author";
		_generalMacro="H_FR2035_Beret_blu";
		displayName="$STR_fr2035_h_beret_blk0";
		picture="\A3\characters_f\Data\UI\icon_H_Beret_blk_CA.paa";
		model="\A3\Characters_F\Common\headgear_beret01";
		hiddenSelectionsTextures[]=
		{
			"\fr2035_characters_f\data\fr2035_beret_co.paa"
		};
	};
};

enum {
	destructengine = 2,
	destructdefault = 6,
	destructwreck = 7,
	destructtree = 3,
	destructtent = 4,
	stabilizedinaxisx = 1,
	stabilizedinaxesxyz = 4,
	stabilizedinaxisy = 2,
	stabilizedinaxesboth = 3,
	destructno = 0,
	stabilizedinaxesnone = 0,
	destructman = 5,
	destructbuilding = 1
}